; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs =
    bike1_ap
    bike2_sta
    bike3_sta

[env]
platform = espressif32
board = m5stack-atoms3
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
lib_deps =
    m5stack/M5Unified

[env:m5stack-atoms3]
extends = env:bike1_ap

[env:bike1_ap]
build_flags =
    ${env.build_flags}
    -DDEVICE_AP_MODE=1
    -DDEVICE_IP_LAST_OCTET=1
    -DOSC_ADDRESS_PREFIX=\"/bike1\"

[env:bike2_sta]
build_flags =
    ${env.build_flags}
    -DDEVICE_AP_MODE=0
    -DDEVICE_IP_LAST_OCTET=2
    -DOSC_ADDRESS_PREFIX=\"/bike2\"

[env:bike3_sta]
build_flags =
    ${env.build_flags}
    -DDEVICE_AP_MODE=0
    -DDEVICE_IP_LAST_OCTET=3
    -DOSC_ADDRESS_PREFIX=\"/bike3\"
